#pragma once
#define EXCEPTION_USER_NOT_FOUND "User not found"
#define EXCEPTION_USER_EXISTS "User already exists"
#define EXCEPTION_COULD_NOT_LOAD_USERS_XML "Could not load users repository XML file"
#define EXCEPTION_COULD_NOT_LOAD_BOOKS_XML "Could not load books repository XML file"
#define EXCEPTION_BOOK_NOT_FOUND "Book not found"
#define EXCEPTION_BOOKS_NOT_FOUND "No books found"
#define EXCEPTION_BOOK_EXISTS "Book with that ID already exists"
#define EXCEPTION_DATE_EMPTY "No date available"
#define EXCEPTION_COULD_NOT_GET_USER_BOOKS "Could not get user books: "
#define EXCEPTION_COULD_NOT_GET_BOOK_USER "Could not get current reader of that book: "
#define EXCEPTION_BOOK_IS_NOT_BORROWED "Book is not currently borrowed"
#define EXCEPTION_COULD_NOT_GET_BORROWED_BOOKS "Could not get borrowed books: "
#define EXCEPTION_COULD_NOT_GET_ALL_BOOKS "Could not get all books: "
#define EXCEPTION_COULD_NOT_GET_USERS_WITH_EXPIRED_BOOKS "Could not get users with expired books: "
#define EXCEPTION_COULD_NOT_LEND_BOOK_TO_USER "Could not lend book to user: "
#define EXCEPTION_BOOK_IS_BORROWED "Book is currently borrowed"
#define EXCEPTION_USER_HAS_BOOK "Book is already borrowed by that user"
#define EXCEPTION_COULD_NOT_RETURN_BOOK_FROM_USER "Could not return book from user: "
#define EXCEPTION_USER_DOES_NOT_HAVE_BOOK "User does not have that book"
#define EXCEPTION_COULD_NOT_ADD_NEW_USER_TO_LIBRARY "Could not add new user to library: "
#define EXCEPTION_USER_HAS_NON_RETURNED_BOOKS "User has not returned all books"
#define EXCEPTION_COULD_NOT_ADD_NEW_BOOK_TO_LIBRARY "Could not add new book to library: "
#define EXCEPTION_COULD_NOT_GET_BOOK "Could not get book: "
#define EXCEPTION_COULD_NOT_GET_USER "Could not get user: "
#define EXCEPTION_COULD_NOT_GET_USERS "Could not get users: "
#define EXCEPTION_COULD_NOT_GET_BOOKS "Could not get books: "
#define EXCEPTION_NO_FREE_BOOKS_FOUND "No free books found"
#define EXCEPTION_COULD_NOT_GET_AVAILABLE_BOOK "Could not get any available book: "
#define EXCEPTION_COULD_NOT_REMOVE_USER_FROM_LIBRARY "Could not remove user from library: "
#define EXCEPTION_COULD_NOT_REMOVE_BOOK_FROM_LIBRARY "Could not remove book from library: "